name: Build/release MarkText+

on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install Linux Build Dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y icnsutils graphicsmagick xz-utils libx11-dev libxkbfile-dev gnome-keyring libsecret-1-dev libfontconfig-dev rpm

      - name: Install Dependencies
        run: npm ci --no-audit --no-fund --ignore-scripts --loglevel verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Electron requires C++20 support for native modules after Electron 33
      - name: Set C++20 for MacOS
        if: runner.os == 'macOS'
        run: |
          echo "CXXFLAGS=-std=gnu++20 -stdlib=libc++" >> $GITHUB_ENV

      - name: build-linux
        if: runner.os == 'Linux'
        run: npm run build:linux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USE_ELECTRON_CLANG: '0'

      - name: build-mac
        if: runner.os == 'macOS'
        run: npm run build:mac
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: build-win
        if: runner.os == 'Windows'
        run: npm run build:win
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          generate_release_notes: true
          name: '${{ github.ref_name }}'
          body: |
            ## Note for MacOS Users
            MacOS releases are **not notarized**. After dragging MarkText+ into Applications, run:
            ```
            xattr -cr /Applications/marktext.app
            sudo codesign --force --deep --sign - /Applications/marktext.app
            ```

            ## Changes
          files: |
            dist/*.exe
            dist/*.zip
            dist/*.dmg
            dist/*.AppImage
            dist/*.snap
            dist/*.deb
            dist/*.rpm
            dist/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
